export const projects = [
  {
    id: 'nano33',
    title: 'TinyML on Nano 33 BLE',
    sub: 'Real-time KWS & gesture recognition',
    tags: ['Arduino Nano 33 BLE', 'CMSIS-NN', 'C++'],
    body: 'Deployed keyword-spotting and gesture-recognition models on a microcontroller under strict memory and latency budgets, with the inference pipeline optimized on CMSIS-NN to fit on-device.',
    specs: [
      { label: 'gesture acc.', value: '0.9871', glossary: 'gestureNote' },
      { label: 'gesture size', value: '13 KB' },
      { label: 'KWS acc.', value: '0.9012' },
      { label: 'KWS size', value: '60 KB' },
      { label: 'flash budget', value: '512 KB' },
      { label: 'hardware', value: 'Nano 33 BLE' },
    ],
    footprint: [
      { width: 11.7, label: '13KB' },
      { width: 2.5, label: '60KB' },
    ],
    note: 'The harder constraint wasn\u2019t accuracy \u2014 it was keeping both models resident in flash at once. CMSIS-NN kernels and aggressive quantization made the 512KB budget work without trading away real-time response.',
    repo: '#',
    has3d: false,
  },
  {
    id: 'ur5',
    title: 'UR5 Robotic Manipulator',
    sub: 'Vision-guided pick-and-place',
    tags: ['ROS2', 'Computer Vision', 'Kinematics'],
    body: 'Real-time robotic control integrating kinematics with vision-based object detection, with synchronization logic for autonomous pick-and-place in a simulated environment.',
    specs: [
      { label: 'object classes', value: '10 block types' },
      { label: 'planning', value: 'automated joint path' },
      { label: 'domain', value: 'simulated' },
      { label: 'stack', value: 'vision + kinematics' },
    ],
    note: 'The detection pipeline had to stay synchronized with joint-path planning in real time \u2014 misalignment between what the camera saw and where the arm thought it was would cause failed grasps.',
    repo: '#',
    has3d: true,
  },
  {
    id: 'hpc',
    title: 'HPC: CUDA SpMV & Matrix Transposition',
    sub: 'Ongoing \u2014 parallel computing study',
    tags: ['CUDA', 'OpenMP', 'MPI'],
    body: 'Sparse matrix\u2013vector multiplication via CUDA (sparse-CU, CSR) alongside a matrix-transposition study using implicit parallelism, OpenMP and MPI, analyzing memory bottlenecks and load balancing across clusters.',
    specs: [
      { label: 'SpMV', value: 'sparse-CU \u00b7 CSR', glossary: 'csr' },
      { label: 'transposition', value: 'OpenMP + MPI' },
      { label: 'focus', value: 'memory bottlenecks, load balance' },
    ],
    note: 'Sparse formats trade compute for memory traffic \u2014 the real work was profiling where the CSR layout helped versus where it just moved the bottleneck from compute-bound to memory-bound.',
    repo: '#',
    has3d: false,
  },
  {
    id: 'telkonet',
    title: 'Telkonet-OMNI',
    sub: 'IoT all-in-one PoC \u2014 ongoing',
    tags: ['IoT', 'Flask', 'Product Strategy'],
    body: 'A proof-of-concept integrated IoT device for hotel rooms, managing sensor acquisition and communication protocols, paired with financial planning and product strategy for Telkonet VDA as part of the Innovation & Entrepreneurship minor.',
    specs: [
      { label: 'scope', value: 'sensors + comms + product strategy' },
      { label: 'context', value: 'EIT Digital Innovation minor' },
      { label: 'partner', value: 'Telkonet VDA' },
    ],
    note: 'This one pairs engineering with the business side \u2014 the EIT Digital minor required treating the PoC as a product decision, not just a technical one, with real cost/benefit tradeoffs.',
    repo: '#',
    has3d: false,
  },
  {
    id: 'mastermind',
    title: 'Embedded Mastermind Simulation',
    sub: 'HCI on bare-metal Cortex-M4',
    tags: ['C', 'Cortex-M4', 'Interrupts'],
    body: 'A full simulation of the Mastermind game on a TI Cortex-M4, integrating human\u2013computer interaction principles with low-level C, managing interrupts from timers, physical buttons and joystick movement, with visual output on the integrated screen.',
    specs: [
      { label: 'hardware', value: 'TI Cortex-M4', glossary: 'cortexm4' },
      { label: 'language', value: 'C' },
      { label: 'I/O', value: 'timers, buttons, joystick, display' },
    ],
    note: 'No OS, no abstraction layer \u2014 every button debounce and timer interrupt is hand-written, which is exactly what makes it a useful HCI exercise on bare metal.',
    repo: '#',
    has3d: false,
  },
  {
    id: 'ctf',
    title: 'Hack-In-Tower CTF',
    sub: 'Bologna, 2025 \u2014 BOOM Knowledge Hub \u00b7 3rd place',
    tags: ['Reverse Engineering', 'Cryptography', 'Network'],
    body: 'Solved security challenges representing CISCO \u2014 reverse engineering, cryptography and network exploitation on a Linux VM, under competition conditions.',
    specs: [
      { label: 'categories', value: 'reversing \u00b7 crypto \u00b7 network' },
      { label: 'result', value: '3rd place' },
    ],
    note: null,
    repo: null,
    has3d: false,
  },
]